FROM docker.io/fedora:latest

USER root

RUN dnf check-update; \
    dnf install -y wget; \
    dnf install -y git-all; \
    dnf install -y gcc glibc-devel zlib-devel libstdc++-static; \
    dnf clean all

RUN wget https://download.oracle.com/graalvm/21/latest/graalvm-jdk-21_linux-x64_bin.tar.gz; \
    tar -xzf graalvm-jdk-21_linux-x64_bin.tar.gz; \
    rm graalvm-jdk-21_linux-x64_bin.tar.gz; \
    wget https://dlcdn.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz; \
    tar -xzf apache-maven-3.9.6-bin.tar.gz; \
    rm apache-maven-3.9.6-bin.tar.gz

RUN mkdir /work; \
    chgrp -R 0 /work && \
    chmod -R g+rwX /work; \
    ln -s /apache-maven-3.9.6/bin/mvn /usr/bin/mvn

WORKDIR /work

ENV JAVA_HOME="/graalvm-jdk-21.0.2+13.1"
ENV M2_HOME="/apache-maven-3.9.6"
ENV PATH="/graalvm-jdk-21.0.2+13.1/bin:/apache-maven-3.9.6/bin:$PATH"
